version: "3.8"

services:
  app:
    build: .
    container_name: streaming-app
    ports:
      - "3344:3344"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads  # <== Montagem de volume aqui
