version: "3.8"

services:
  app:
    build: .
    container_name: streaming-app
    ports:
      - "3344:3344"
    env_file:
      - .env
    volumes:
      - /www/wwwroot/test/STREAMING-APP/uploads:/app/uploads
