// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"stream/ent/file"
	"stream/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileUpdate is the builder for updating File entities.
type FileUpdate struct {
	config
	hooks    []Hook
	mutation *FileMutation
}

// Where appends a list predicates to the FileUpdate builder.
func (fu *FileUpdate) Where(ps ...predicate.File) *FileUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetUpdateTime sets the "update_time" field.
func (fu *FileUpdate) SetUpdateTime(t time.Time) *FileUpdate {
	fu.mutation.SetUpdateTime(t)
	return fu
}

// SetFileName sets the "file_name" field.
func (fu *FileUpdate) SetFileName(s string) *FileUpdate {
	fu.mutation.SetFileName(s)
	return fu
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (fu *FileUpdate) SetNillableFileName(s *string) *FileUpdate {
	if s != nil {
		fu.SetFileName(*s)
	}
	return fu
}

// SetVisibility sets the "visibility" field.
func (fu *FileUpdate) SetVisibility(b bool) *FileUpdate {
	fu.mutation.SetVisibility(b)
	return fu
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (fu *FileUpdate) SetNillableVisibility(b *bool) *FileUpdate {
	if b != nil {
		fu.SetVisibility(*b)
	}
	return fu
}

// SetStatus sets the "status" field.
func (fu *FileUpdate) SetStatus(s string) *FileUpdate {
	fu.mutation.SetStatus(s)
	return fu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (fu *FileUpdate) SetNillableStatus(s *string) *FileUpdate {
	if s != nil {
		fu.SetStatus(*s)
	}
	return fu
}

// SetStatusDetails sets the "status_details" field.
func (fu *FileUpdate) SetStatusDetails(s string) *FileUpdate {
	fu.mutation.SetStatusDetails(s)
	return fu
}

// SetNillableStatusDetails sets the "status_details" field if the given value is not nil.
func (fu *FileUpdate) SetNillableStatusDetails(s *string) *FileUpdate {
	if s != nil {
		fu.SetStatusDetails(*s)
	}
	return fu
}

// ClearStatusDetails clears the value of the "status_details" field.
func (fu *FileUpdate) ClearStatusDetails() *FileUpdate {
	fu.mutation.ClearStatusDetails()
	return fu
}

// SetMetadata sets the "metadata" field.
func (fu *FileUpdate) SetMetadata(m map[string]interface{}) *FileUpdate {
	fu.mutation.SetMetadata(m)
	return fu
}

// ClearMetadata clears the value of the "metadata" field.
func (fu *FileUpdate) ClearMetadata() *FileUpdate {
	fu.mutation.ClearMetadata()
	return fu
}

// SetCreatedAt sets the "created_at" field.
func (fu *FileUpdate) SetCreatedAt(t time.Time) *FileUpdate {
	fu.mutation.SetCreatedAt(t)
	return fu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fu *FileUpdate) SetNillableCreatedAt(t *time.Time) *FileUpdate {
	if t != nil {
		fu.SetCreatedAt(*t)
	}
	return fu
}

// SetDeletedAt sets the "deleted_at" field.
func (fu *FileUpdate) SetDeletedAt(t time.Time) *FileUpdate {
	fu.mutation.SetDeletedAt(t)
	return fu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fu *FileUpdate) SetNillableDeletedAt(t *time.Time) *FileUpdate {
	if t != nil {
		fu.SetDeletedAt(*t)
	}
	return fu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (fu *FileUpdate) ClearDeletedAt() *FileUpdate {
	fu.mutation.ClearDeletedAt()
	return fu
}

// Mutation returns the FileMutation object of the builder.
func (fu *FileUpdate) Mutation() *FileMutation {
	return fu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FileUpdate) Save(ctx context.Context) (int, error) {
	fu.defaults()
	return withHooks(ctx, fu.sqlSave, fu.mutation, fu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FileUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FileUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FileUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fu *FileUpdate) defaults() {
	if _, ok := fu.mutation.UpdateTime(); !ok {
		v := file.UpdateDefaultUpdateTime()
		fu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fu *FileUpdate) check() error {
	if v, ok := fu.mutation.FileName(); ok {
		if err := file.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "File.file_name": %w`, err)}
		}
	}
	return nil
}

func (fu *FileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(file.Table, file.Columns, sqlgraph.NewFieldSpec(file.FieldID, field.TypeString))
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.UpdateTime(); ok {
		_spec.SetField(file.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := fu.mutation.FileName(); ok {
		_spec.SetField(file.FieldFileName, field.TypeString, value)
	}
	if value, ok := fu.mutation.Visibility(); ok {
		_spec.SetField(file.FieldVisibility, field.TypeBool, value)
	}
	if value, ok := fu.mutation.Status(); ok {
		_spec.SetField(file.FieldStatus, field.TypeString, value)
	}
	if value, ok := fu.mutation.StatusDetails(); ok {
		_spec.SetField(file.FieldStatusDetails, field.TypeString, value)
	}
	if fu.mutation.StatusDetailsCleared() {
		_spec.ClearField(file.FieldStatusDetails, field.TypeString)
	}
	if value, ok := fu.mutation.Metadata(); ok {
		_spec.SetField(file.FieldMetadata, field.TypeJSON, value)
	}
	if fu.mutation.MetadataCleared() {
		_spec.ClearField(file.FieldMetadata, field.TypeJSON)
	}
	if value, ok := fu.mutation.CreatedAt(); ok {
		_spec.SetField(file.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := fu.mutation.DeletedAt(); ok {
		_spec.SetField(file.FieldDeletedAt, field.TypeTime, value)
	}
	if fu.mutation.DeletedAtCleared() {
		_spec.ClearField(file.FieldDeletedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fu.mutation.done = true
	return n, nil
}

// FileUpdateOne is the builder for updating a single File entity.
type FileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileMutation
}

// SetUpdateTime sets the "update_time" field.
func (fuo *FileUpdateOne) SetUpdateTime(t time.Time) *FileUpdateOne {
	fuo.mutation.SetUpdateTime(t)
	return fuo
}

// SetFileName sets the "file_name" field.
func (fuo *FileUpdateOne) SetFileName(s string) *FileUpdateOne {
	fuo.mutation.SetFileName(s)
	return fuo
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (fuo *FileUpdateOne) SetNillableFileName(s *string) *FileUpdateOne {
	if s != nil {
		fuo.SetFileName(*s)
	}
	return fuo
}

// SetVisibility sets the "visibility" field.
func (fuo *FileUpdateOne) SetVisibility(b bool) *FileUpdateOne {
	fuo.mutation.SetVisibility(b)
	return fuo
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (fuo *FileUpdateOne) SetNillableVisibility(b *bool) *FileUpdateOne {
	if b != nil {
		fuo.SetVisibility(*b)
	}
	return fuo
}

// SetStatus sets the "status" field.
func (fuo *FileUpdateOne) SetStatus(s string) *FileUpdateOne {
	fuo.mutation.SetStatus(s)
	return fuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (fuo *FileUpdateOne) SetNillableStatus(s *string) *FileUpdateOne {
	if s != nil {
		fuo.SetStatus(*s)
	}
	return fuo
}

// SetStatusDetails sets the "status_details" field.
func (fuo *FileUpdateOne) SetStatusDetails(s string) *FileUpdateOne {
	fuo.mutation.SetStatusDetails(s)
	return fuo
}

// SetNillableStatusDetails sets the "status_details" field if the given value is not nil.
func (fuo *FileUpdateOne) SetNillableStatusDetails(s *string) *FileUpdateOne {
	if s != nil {
		fuo.SetStatusDetails(*s)
	}
	return fuo
}

// ClearStatusDetails clears the value of the "status_details" field.
func (fuo *FileUpdateOne) ClearStatusDetails() *FileUpdateOne {
	fuo.mutation.ClearStatusDetails()
	return fuo
}

// SetMetadata sets the "metadata" field.
func (fuo *FileUpdateOne) SetMetadata(m map[string]interface{}) *FileUpdateOne {
	fuo.mutation.SetMetadata(m)
	return fuo
}

// ClearMetadata clears the value of the "metadata" field.
func (fuo *FileUpdateOne) ClearMetadata() *FileUpdateOne {
	fuo.mutation.ClearMetadata()
	return fuo
}

// SetCreatedAt sets the "created_at" field.
func (fuo *FileUpdateOne) SetCreatedAt(t time.Time) *FileUpdateOne {
	fuo.mutation.SetCreatedAt(t)
	return fuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fuo *FileUpdateOne) SetNillableCreatedAt(t *time.Time) *FileUpdateOne {
	if t != nil {
		fuo.SetCreatedAt(*t)
	}
	return fuo
}

// SetDeletedAt sets the "deleted_at" field.
func (fuo *FileUpdateOne) SetDeletedAt(t time.Time) *FileUpdateOne {
	fuo.mutation.SetDeletedAt(t)
	return fuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fuo *FileUpdateOne) SetNillableDeletedAt(t *time.Time) *FileUpdateOne {
	if t != nil {
		fuo.SetDeletedAt(*t)
	}
	return fuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (fuo *FileUpdateOne) ClearDeletedAt() *FileUpdateOne {
	fuo.mutation.ClearDeletedAt()
	return fuo
}

// Mutation returns the FileMutation object of the builder.
func (fuo *FileUpdateOne) Mutation() *FileMutation {
	return fuo.mutation
}

// Where appends a list predicates to the FileUpdate builder.
func (fuo *FileUpdateOne) Where(ps ...predicate.File) *FileUpdateOne {
	fuo.mutation.Where(ps...)
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *FileUpdateOne) Select(field string, fields ...string) *FileUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated File entity.
func (fuo *FileUpdateOne) Save(ctx context.Context) (*File, error) {
	fuo.defaults()
	return withHooks(ctx, fuo.sqlSave, fuo.mutation, fuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FileUpdateOne) SaveX(ctx context.Context) *File {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FileUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FileUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fuo *FileUpdateOne) defaults() {
	if _, ok := fuo.mutation.UpdateTime(); !ok {
		v := file.UpdateDefaultUpdateTime()
		fuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fuo *FileUpdateOne) check() error {
	if v, ok := fuo.mutation.FileName(); ok {
		if err := file.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "File.file_name": %w`, err)}
		}
	}
	return nil
}

func (fuo *FileUpdateOne) sqlSave(ctx context.Context) (_node *File, err error) {
	if err := fuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(file.Table, file.Columns, sqlgraph.NewFieldSpec(file.FieldID, field.TypeString))
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "File.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, file.FieldID)
		for _, f := range fields {
			if !file.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != file.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.UpdateTime(); ok {
		_spec.SetField(file.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.FileName(); ok {
		_spec.SetField(file.FieldFileName, field.TypeString, value)
	}
	if value, ok := fuo.mutation.Visibility(); ok {
		_spec.SetField(file.FieldVisibility, field.TypeBool, value)
	}
	if value, ok := fuo.mutation.Status(); ok {
		_spec.SetField(file.FieldStatus, field.TypeString, value)
	}
	if value, ok := fuo.mutation.StatusDetails(); ok {
		_spec.SetField(file.FieldStatusDetails, field.TypeString, value)
	}
	if fuo.mutation.StatusDetailsCleared() {
		_spec.ClearField(file.FieldStatusDetails, field.TypeString)
	}
	if value, ok := fuo.mutation.Metadata(); ok {
		_spec.SetField(file.FieldMetadata, field.TypeJSON, value)
	}
	if fuo.mutation.MetadataCleared() {
		_spec.ClearField(file.FieldMetadata, field.TypeJSON)
	}
	if value, ok := fuo.mutation.CreatedAt(); ok {
		_spec.SetField(file.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.DeletedAt(); ok {
		_spec.SetField(file.FieldDeletedAt, field.TypeTime, value)
	}
	if fuo.mutation.DeletedAtCleared() {
		_spec.ClearField(file.FieldDeletedAt, field.TypeTime)
	}
	_node = &File{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{file.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuo.mutation.done = true
	return _node, nil
}
