// Code generated by ent, DO NOT EDIT.

package ent

import (
	"stream/ent/file"
	"stream/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fileMixin := schema.File{}.Mixin()
	fileMixinFields0 := fileMixin[0].Fields()
	_ = fileMixinFields0
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescCreateTime is the schema descriptor for create_time field.
	fileDescCreateTime := fileMixinFields0[0].Descriptor()
	// file.DefaultCreateTime holds the default value on creation for the create_time field.
	file.DefaultCreateTime = fileDescCreateTime.Default.(func() time.Time)
	// fileDescUpdateTime is the schema descriptor for update_time field.
	fileDescUpdateTime := fileMixinFields0[1].Descriptor()
	// file.DefaultUpdateTime holds the default value on creation for the update_time field.
	file.DefaultUpdateTime = fileDescUpdateTime.Default.(func() time.Time)
	// file.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	file.UpdateDefaultUpdateTime = fileDescUpdateTime.UpdateDefault.(func() time.Time)
	// fileDescFileName is the schema descriptor for file_name field.
	fileDescFileName := fileFields[1].Descriptor()
	// file.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	file.FileNameValidator = fileDescFileName.Validators[0].(func(string) error)
	// fileDescVisibility is the schema descriptor for visibility field.
	fileDescVisibility := fileFields[2].Descriptor()
	// file.DefaultVisibility holds the default value on creation for the visibility field.
	file.DefaultVisibility = fileDescVisibility.Default.(bool)
	// fileDescStatus is the schema descriptor for status field.
	fileDescStatus := fileFields[3].Descriptor()
	// file.DefaultStatus holds the default value on creation for the status field.
	file.DefaultStatus = fileDescStatus.Default.(string)
	// fileDescCreatedAt is the schema descriptor for created_at field.
	fileDescCreatedAt := fileFields[6].Descriptor()
	// file.DefaultCreatedAt holds the default value on creation for the created_at field.
	file.DefaultCreatedAt = fileDescCreatedAt.Default.(func() time.Time)
}
