// Code generated by ent, DO NOT EDIT.

package ent

import (
	"stream/ent/file"
	"stream/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescFile is the schema descriptor for file field.
	fileDescFile := fileFields[0].Descriptor()
	// file.FileValidator is a validator for the "file" field. It is called by the builders before save.
	file.FileValidator = fileDescFile.Validators[0].(func(string) error)
}
